name: ci-build

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install dependencies & check packages vulnerabilities
      run: |
        cd node-hello
        npm install
    # - name: Run tests
    #   run: npm test
    - name: 'create SHORT_SHA env var- for versioning'
      run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV
    - name: docker steps
      run: |            
        docker login -u="${{ secrets.DOCKER_USER }}" -p="${{ secrets.DOCKER_PASS }}"
        docker build -t ${GITHUB_REPOSITORY}-node-hello:${SHORT_SHA} ./ 
        docker push ${GITHUB_REPOSITORY}-node-hello:${SHORT_SHA}
